# Generated by Django 6.0.3 on 2026-06-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvmaker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='education',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cv',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='cv',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cv',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cv',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cv',
            name='profile',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cv',
            name='projects',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cv',
            name='experience',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cv',
            name='skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cv',
            name='template',
            field=models.CharField(default='simple', max_length=50),
        ),
    ]
